In [2]:
import networkx as nx
import numpy as np
from lib import get_embeddings, get_adj
import random

G = nx.karate_club_graph().to_directed()
for (u, v) in G.edges:
    G.edges[u, v]['weight'] = random.random()

print(get_adj(G))

[[0.         0.81694104 0.65936629 ... 0.27687826 0.         0.        ]
 [0.29294686 0.         0.46372553 ... 0.         0.         0.        ]
 [0.24589146 0.4247253  0.         ... 0.         0.05977206 0.        ]
 ...
 [0.88058984 0.         0.         ... 0.         0.38909641 0.86557823]
 [0.         0.         0.42836295 ... 0.93413949 0.         0.58146096]
 [0.         0.         0.         ... 0.44183225 0.70478548 0.        ]]


In [3]:
N = len(G.nodes)
q = 0.2
S = np.arange(10)*0.1
T = np.arange(10)*0.1

embeddings = get_embeddings(G, S, T, q)
print(embeddings.shape)

(34, 200)


In [4]:
embeddings[0]

array([1.        , 0.99985306, 0.99941372, 0.99868637, 0.99767826,
       0.99639949, 0.99486281, 0.99308359, 0.99107961, 0.98887088,
       1.        , 0.99987987, 0.99965169, 0.99931605, 0.99887389,
       0.99832653, 0.99767567, 0.99692334, 0.99607198, 0.99512432,
       1.        , 0.99987534, 0.99968975, 0.9994434 , 0.99913657,
       0.99876962, 0.99834306, 0.99785746, 0.99731354, 0.99671209,
       1.        , 0.99986931, 0.99969689, 0.99948282, 0.99922722,
       0.99893023, 0.99859207, 0.99821298, 0.99779325, 0.99733321,
       1.        , 0.99986438, 0.9996969 , 0.9994976 , 0.99926653,
       0.99900378, 0.99870945, 0.99838368, 0.99802661, 0.99763841,
       1.        , 0.99986063, 0.99969522, 0.99950379, 0.99928639,
       0.99904307, 0.99877388, 0.99847891, 0.99815825, 0.99781199,
       1.        , 0.99985781, 0.99969337, 0.99950668, 0.99929779,
       0.99906673, 0.99881353, 0.99853826, 0.99824096, 0.9979217 ,
       1.        , 0.99985571, 0.9996918 , 0.99950828, 0.99930